# Generated by Django 2.2 on 2019-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
